
on: [push]    
    #push:
       #branches: [dev]
    #pull_request:
        #branches: [master]
jobs: 
    cicd:
        uses: PrinceMargaret/workflow-template/.github/workflows/workflow.yml@master
        with:
            appName: github-action-cicd-demo-1
            appVersion: 1.0.${{ github.run_number }}
           
        secrets: inherit

        