on:     
    push:
       branches: [dev]
    pull_request:
        branches: [master]
jobs:
    cicd:
        uses: PrinceMargaret/github-action/blob/master/.github/workflows/workflow.yml@master
        with:
            app_name: cicd_demo_ccc