on:     
    push:
       branches: [dev]
    pull_request:
        branches: [master]
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            run: echo "firstword=hello"

    cicd:
        uses: PrinceMargaret/github-action/.github/workflows/workflow.yml@master
        with:
            app_name: cicd_demo_ccc